name: Build

on:
  push:
    branches:
    - development
    - action_fixes
#    - '[0-9]+.[0-9]+.x'

  workflow_dispatch: ~

jobs:
  build-images:
    name: Build and push image - ${{ matrix.image-name }}
    runs-on: ubuntu-latest

    # let's not run this on every fork, change to your fork when developing
    if: github.repository == 'hedingber/mlrun'

    strategy:
      matrix:
        image-name:
        - mlrun
        - api
        - base
        - base-legacy
        - models
        - models-legacy
        - test
# The GPU images are too big (~24GB) GH action runner has only 14GB
#        - models-gpu
#        - models-gpu-legacy
    steps:
    - uses: actions/checkout@v2
    - name: Install curl and jq
      run: sudo apt-get install curl jq
    - name: Extract git hashes and latest version
      id: git_info
      run: |
        echo "::set-output name=mlrun_commit_hash::$(git rev-parse --short $GITHUB_SHA)"
        echo "::set-output name=latest_version::$(curl -sf https://pypi.org/pypi/mlrun/json | jq -r '.info.version')"
    - name: Set computed versions params
      id: computed_params
      run: |
        echo "::set-output name=mlrun_version::${{ steps.git_info.outputs.latest_version }}-${{ steps.git_info.outputs.mlrun_commit_hash }}"
        echo "::set-output name=mlrun_docker_repo::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')"
    - name: Docker login
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ secrets.CR_USERNAME }} --password-stdin
    - name: Pull cache, build and push image

      # we don't really want per-commit test image we just want to build and push the cache image so CI will be able
      # to use it and run much faster
      if: ${{ matrix.image-name != 'test' }}
      run: |
        MLRUN_DOCKER_REGISTRY=ghcr.io/ \
        MLRUN_DOCKER_REPO=${{ steps.computed_params.outputs.mlrun_docker_repo }} \
        MLRUN_VERSION=${{ steps.computed_params.outputs.mlrun_version }} \
        MLRUN_DOCKER_CACHE_FROM_TAG=unstable-cache \
        make push-${{ matrix.image-name }}
    - name: Pull cache, build and push test image
      if: ${{ matrix.image-name == 'test' }}
      run: |
        MLRUN_DOCKER_REGISTRY=ghcr.io/ \
        MLRUN_DOCKER_REPO=${{ steps.computed_params.outputs.mlrun_docker_repo }} \
        MLRUN_VERSION=unstable-cache \
        MLRUN_DOCKER_CACHE_FROM_TAG=unstable-cache \
        make push-${{ matrix.image-name }}
