name: Build

on:
  push:
    branches:
    - build_actions
#    - development
#    - '[0-9]+.[0-9]+.x'

jobs:
  build-images:
    name: Build and push image - ${{ matrix.image-name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [mlrun, api]
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ secrets.CR_USERNAME }} --password-stdin
    - name: Set GIT_HASH env var
      run: echo '::set-env name=SELECTED_COLOR::$(echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin)'
    - name: Build and push image
      run: MLRUN_DOCKER_REGISTRY=ghcr.io/ MLRUN_DOCKER_TAG=unstable-"$GIT_HASH" MLRUN_ADD_DOCKER_CACHE_FROM=true make push-${{ matrix.image-name }}
      # log out at the end cause we're using caching docker stuff
    - name: Docker logout
      run: docker logout ghcr.io
