name: Build

on:
  push:
    branches:
    - build_actions
#    - development
#    - '[0-9]+.[0-9]+.x'

jobs:
  build-images:
    name: Build and push image - ${{ matrix.image-name }}
    if: github.repository == 'hedingber/mlrun'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [mlrun, api]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Print ref
      run: echo ${{ github.ref }}
    - name: Docker login
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ secrets.CR_USERNAME }} --password-stdin
    - name: Set GIT_HASH env var
      run: echo "::set-env name=GIT_HASH::$(git rev-parse --short $GITHUB_SHA)"
    - name: Set PREVIOUS_GIT_HASH env var
      run: |
        export PREVIOUS_GIT_HASH=$(git rev-parse --short "$GITHUB_SHA^")
        echo "::set-env name=PREVIOUS_GIT_HASH::$PREVIOUS_GIT_HASH"
    - name: Enable docker buildkit
      run: echo "::set-env name=DOCKER_BUILDKIT::1"
    - name: Build and push image
      run: MLRUN_DOCKER_REGISTRY=ghcr.io/ MLRUN_DOCKER_TAG=unstable-"$GIT_HASH" MLRUN_DOCKER_CACHE_FROM_TAG=unstable-"$PREVIOUS_GIT_HASH" make push-${{ matrix.image-name }}
